### ISSUE TITLE
when executed in a terminal normal keys gets printed twice

### ISSUE THREAD

**Issue by budRich** [anko/xkbcat#3]
Hello anko. Nice tool! I will replace my `xev | awk ..` dirthack with this.

I know it is not really meant to be used directly in a terminal, but there is the simple usecase just to see the name of a character.
But since termio have the echo flag set to on by default, any keypress inside a terminal will print that character. This means they get printed twice with xkbcat. This is a fix for that:  

``` c
#include <termios.h>
...
    // Turn off echo
    struct termios t;
    if (! tcgetattr(0, &t)) {
        tcgetattr(0, &t);
        t.c_lflag &= ~((tcflag_t) ECHO);
        tcsetattr(0, TCSANOW, &t);
    }

while ("forever") {
...
```

**Comment by anko** [comment]
Hi!  Good to hear it's useful. :sparkles: 

I think changing terminal line settings is a separate task, for a separate program.  Coreutils `stty` can do the same:

```sh
stty -echo && xkbcat
```

If we call `tcsetattr`, another user who needs echo to be on for their use-case wouldn't be able to fix it with `stty`, because `tcsetattr` would override it.  (I can't imagine their use-case, but I hadn't thought of yours either before now! :smile:)

I'll add a mention of `stty` to the readme though.
