### ISSUE TITLE
change parameters order for the compiler

### ISSUE THREAD

**Issue by xorbug** [anko/xkbcat#4]
On `gcc (Debian 10.2.0-19) 10.2.0` build fails with lots of undefined references to X symbols. Specifying the source filename before the libraries in the Makefile fixes it:

```
-       $(CC) -O3 --std=c99 -pedantic -Wall -lX11 -lXi -o xkbcat xkbcat.c
+       $(CC) -O3 --std=c99 -pedantic -Wall xkbcat.c -lX11 -lXi -o xkbcat
```
Bye and thanks for this handy tool.

**Comment by anko** [comment]
Fixed and tested.  Thanks for the report! :sparkles:

- - -

Notes for posterity:

This reproduced on `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` in [this Travis job](https://travis-ci.org/github/anko/xkbcat/jobs/749422942).

Oddly, gcc 9.3.0 on my local Void Linux works, and clang works both locally and on Travis.

Perhaps a mystery Debian patch makes GCC linker flags extra pedantic?  The order I was passing arguments was [incorrect](https://stackoverflow.com/a/409470), but I'd have expected all compilers on all platforms to fail, since I didn't specify `-Wl,--start-group` or any other linker magic.
