### ISSUE TITLE
Wrong or missing output when switching keyboard layout

### ISSUE THREAD

**Issue by unxed** [anko/xkbcat#5]
xkbcat always prints alphabetic chars in english keyboard layout. Can characters translated to currently selected keyboard layout be printed also?

**Comment by unxed** [comment]
https://gist.github.com/unxed/f331e27191b7de12ffaa27d01a862f6d

**Comment by anko** [comment]
Thanks for the report!

When testing this, I was at first confused:  I use a Japanese keyboard with a Japanese layout, and xkbcat prints the correct characters, not English layout ones. But if I change to *English (US)* layout, xkbcat continues printing according to Japanese layout, not English.

So this must be what `XkbKeycodeToKeysym`'s `group` argument does!  0 means always using the *first keyboard layout* in the list, which your machine must have set to English, and mine to Japanese.  Changing it to read from `XkbStateRec` as in your gist makes it work also when switching layouts.  I didn't know this.

[ Aside: How did you know this?? :zany_face: I couldn't find any documentation that properly explained `group`, and all uses of the function I saw just set it to 0. ] 

On my machine,

```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     jp,de,jp
variant:    ,,kana
```

On your machine, I imagine you see `layout: en` instead, followed by other layouts?

**Comment by unxed** [comment]
> How did you know this?

Guessed while reading this:
https://github.com/nonpop/xkblayout-state/blob/master/XKeyboard.cpp

> On your machine, I imagine you see layout: en instead, followed by other layouts?

yep,
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,ru
variant:    ,
options:    terminate:ctrl_alt_bksp,grp:lalt_lshift_toggle,lv3:ralt_switch,misc:typo
```

**Comment by anko** [comment]
Found [the xkb docs regarding groups](https://www.x.org/releases/X11R7.6/doc/libX11/specs/XKB/xkblib.html). A relevant quote, for posterity:

> The Xkb extension supports up to four keysym groups. Groups are named beginning with one and indexed beginning with zero. [...]
>
> Changing to a different group changes the keyboard state to produce characters from a different group. Groups are typically used to switch between keysyms of different languages and locales.

I implemented this in https://github.com/anko/xkbcat/commit/dc5d4e0919b2f1fd18aee16468a23a6631c26251, so the correct keysyms should now be printed also when changing keyboard layouts.  I did it a little bit differently from your example code, by listening for `XkbStateNotify` events to react to keyboard layout changes. This avoids having to call `XkbGetState` repeatedly, which is nice on low-powered machines or remote X servers.

Thanks again for your help. This is a big improvement.

I won't add translation to Unicode symbols (`xkb_keysym_to_utf8`).  It's a cool feature, but I want this program to stay focused only on *what keys were pressed* (rather than on what text those keys cause to be written). Keysyms are the standard way to express that, and they're used by various other X11 programs and config files.  The feature would also mean having to depend on libxkbcommon and adding more code paths, all of which I'd like to avoid to keep this program easy to audit and trust.

**Comment by unxed** [comment]
Now numeric keypad stops working after switching to non-latin layout

**Comment by anko** [comment]
Interesting. You're right. The keypad keys aren't printed.

I will investigate.

**Comment by anko** [comment]
https://github.com/anko/xkbcat/commit/0b9c1bce1f71fa870e624055a86e6fb73690dfde should do it.  It seems the correct solution is to defer to group `0` if the current group is `>0` and finds `NoSymbol`.  Let me know if you notice any other issues.
